---
title: "R code for Malukiewicz et al. Callithrix Microbiomes"
output: html_notebook
---

```{r alpha diversity GLM}


library(multcomp)

#load data with host bacterial feature observed counts which can be obtained from Supplementary Table S1

data.obs=read.csv("bacterial_feature_counts.csv", header=TRUE)

data.obs$species=as.factor(data.obs$species)
data.obs$captive=as.factor(data.obs$captive)


#build glm 
obs.m1=glm(value ~ species+captive, data=data.obs, family=poisson)


#check results 

summary(obs.m1)

anova(obs.m1, test="Chisq")

#multiple testing

K1 <- glht(obs.m1, mcp(captive = "Tukey"))$linfct
K2 <- glht(obs.m1, mcp(species = "Tukey"))$linfct
summary(glht(obs.m1, linfct = rbind(K1, K2)))



#diagostic plots 
p=plot(obs.m1)

p

coef(summary(obs.m1))

#diagostic plots 
 
scatter.smooth(rstandard(obs.m1)~log(fitted(obs.m1)), las=1, ylab="Standardized deviance residual", xlab="Fitted Values")

scatter.smooth(rstandard(obs.m1)~data.obs$captive, las=1, ylab="Standardized deviance residual", xlab="captive")

scatter.smooth(rstandard(obs.m1)~data.obs$species, las=1, ylab="Standardized deviance residual", xlab="species")


#check wether the link funciton is appropriate
z=resid(obs.m1, type="working")+ obs.m1$linear.predictor

plot(z~obs.m1$linear.predictor, las=1, xlab="Working response, z" ,ylab="Linear predictor")

abline(0,1)



termplot(obs.m1, partial.resid = TRUE, las=1)


#influential outliers 

im=influence.measures(obs.m1)
names(im)            
               
im$infmat=round(im$infmat, 3); head(im$infmat)

colSums(im$is.inf)


#plots of influential statistics
obs.cd=cooks.distance(obs.m1)
plot(obs.cd, type="h", ylab="Cooks", las=1)
infl=which.max(obs.cd)
obs.cd[infl]


top_x_outlier <- 1
influential <- as.numeric(names(sort(obs.cd, decreasing = TRUE)[1:top_x_outlier]))


```


```{r NMDS bacterial features}

library(MASS)
library(vegan)

data=read.csv("table.from_biom_vegan_transpose.csv" , header=TRUE)

#make community matrix by extracting  columns with abundance information
com = data[,4:ncol(data)]

#turn abundance data frame into a matrix
m_com = as.matrix(com)

set.seed(123)
nmds = metaMDS(m_com, distance = "bray")
nmds

plot(nmds)

#extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds))

#add columns to data frame 
data.scores$Sample = data$Sample
data.scores$Species = data$Species
data.scores$Captive = data$Captive
 
head(data.scores)

library(ggplot2)

#plot NMDS results 

xx = ggplot(data.scores, aes(x = NMDS1, y = NMDS2))+ 
    geom_point(size = 4, aes( shape = Captive, colour = Species))
 
 
xx



```


```{r phyloseq make phyloseq object out of bacterial feature counts}
#follows http://deneflab.github.io/MicrobeMiseq/demos/mothur_2_phyloseq.html
#if (!requireNamespace("BiocManager", quietly = TRUE))
   # install.packages("BiocManager")

#BiocManager::install("phyloseq")



library(phyloseq)


#set up phyloseq object 
#data import 
#https://vaulot.github.io/tutorials/Phyloseq_tutorial.html followed for reference 
otu_mat=read.table("otu_table.txt",header=TRUE)


#Phyloseq objects need to have row.names, define the row names from the otu column

otu_mat <- otu_mat %>%
    tibble::column_to_rownames("OTUID") 

tax_mat=read.table("taxonomy_phyloseq.tsv",header=TRUE)

 tax_mat <- tax_mat %>% 
    tibble::column_to_rownames("OTUID")
 
 samples_df=read.table("phyloseq.txt",header=TRUE)
 
 samples_df <- samples_df %>% 
    tibble::column_to_rownames("HostID")
 
 #transform into matrixes out and tax table 
 otu_mat <- as.matrix(otu_mat)
  tax_mat <- as.matrix(tax_mat)
  
#transform to phloseq objects 
OTU = otu_table(otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(tax_mat)
samples = sample_data(samples_df)
  
marmo <- phyloseq(OTU, TAX, samples)
  
  
```

```{r permanova of bacterial feature counts}
#https://github.com/kdyson/R_Scripts/blob/master/AICc_PERMANOVA.R

# Calculate bray curtis distance matrix
marmoset_bray <- phyloseq::distance(marmo, method = "bray")

library(EcolUtils)
#make data frame of sample data 
sampledf <- data.frame(sample_data(marmo))

#run adonis2



m12=adonis2(marmoset_bray~ captive+species, data=sampledf, by="margin")
m12


bray.marmo=vegdist(m_com, method="bray")
samples_df$captive=as.factor(samples_df$captive)
adonis.pair(bray.marmo, samples_df$captive, nper = 1000, corr.method = "fdr")







```






```{r  calculate percentages of bacterial abundance}
abund=read.csv("transpose_abundance_captive.csv",header=TRUE)
abund=as_tibble(abund)

abundw=filter(abund, captive =="W")
abundc=filter(abund, captive =="C")
abunds=filter(abund, captive =="S")


abundj=filter(abund, captive =="S")



mean(abundw$c__Actinobacteria)
 mean(abundc$c__Gammaproteobacteria)
mean(abunds$c__Campylobacteria)
mean(abunds$c__Bacteroidia)


abund2=read.csv("åtranspose_abundance_species.csv",header=TRUE)
abund2=as_tibble(abund2)

abundj=filter(abund2, species =="J")
abundp=filter(abund2, species =="P")
abundg=filter(abund2, species =="G")
abunda=filter(abund2, species =="A")
abundjp=filter(abund2, species =="JP")
abundspg=filter(abund2, species =="PG")



```

